name = "ForestInventory"
uuid = "d3650ffc-a530-4289-b27b-e6a44e3508d3"
authors = ["Renilson Lisboa Júnior <renilsonlisboajunior@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
